<a href="https://colab.research.google.com/github/krissydolor/Linear-Algebra-_-2nd-Sem/blob/main/Assignment3_Baniquit_Dolor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra for ChE
## Laboratory 4: Matrices

### Objectives

#### At the end of this activity you will be able to:

#### 1. Be familiar with matrices and their relation to linear equations.
#### 2. Perform basic matrix operations
#### 3. Program and translate matrix equations and operatrions using Python

# Discussion

In [ ]:
import numpy as np
import matplotlib.pyplot as pit
import scipy.linalg as la
%matplotlib inline

### Matrices

###### The notation and use of matrices is probably one of the fundamentals of modern computing. Matrices are also handy representations of complex equations or multiple inter-related equations from 2-dimensional rquations to even hundreds and thousands of them.



###### Let's say for example you have $A$ and $B$ as system of equation

$$
A = \left\{
    \begin{array}\
        x + y \\ 
        4x - 10y
    \end{array}
\right. \\
B = \left\{
    \begin{array}\
        x+y+z \\ 
        3x -2y -z \\
        -x + 4y +2z
    \end{array}
\right. \\
C = \left\{
    \begin{array}\
        w-2x+3y-4z \\ 
        3w -x -2y -z \\
        2w -x + 4y +2z
    \end{array}
\right. $$

###### We could see that $A$ is a system of 2 equations with 2 parameters. While $B$ is a systme of 3 equations with 3 parameters. We can represent them as matrices as:

:$$
A=\begin{bmatrix} 1 & 1 \\ 4 & {-10}\end{bmatrix} \\
B=\begin{bmatrix} 1 & 1 & 1 \\ 3 & -2 & -1 \\ -1 & 4 & 2\end{bmatrix} \\
C=\begin{bmatrix} 1 & -2 & 3 & -4 \\ 3 & -1 & -2 & 1 \\ 2 & -1 & 3 & -2\end
{bmatrix}
$$


###### So assuming that you already discussed the funddamental representation

### Declaring Matrices

The components of a matrix are the entities or values in matrices. Matrices have a category form in which these elements are structured and sorted in rows and columns. Additionally, these categorized elements align to their rows and columns, as with arrays. This can be expressed in the same manner as the expression below. Whereas $A$ is a matrix made up of elements represented by $a_{i,j}$. The number of rows in the matrix is expressed by $i$, meanwhile the number of columns.<br> is denoted by $j$. 

$$A=\begin{bmatrix}
a_{(0,0)}&a_{(0,1)}&\dots&a_{(0,j-1)}\\
a_{(1,0)}&a_{(1,1)}&\dots&a_{(1,j-1)}\\
\vdots&\vdots&\ddots&\vdots&\\
a_{(i-1,0)}&a_{(i-1,1)}&\dots&a_{(i-1,j-1)}
\end{bmatrix}
$$


In [ ]:
## Since we'll keep on describing matrices. Let's make a function
def describe_mat(matrix):
  print(f'Matrix:\n {matrix} \n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [ ]:
## Declaring a 2x2 matrix
A = np.array([
    [2, 3],
    [5, 4]
])
describe_mat(A)

Matrix:
 [[2 3]
 [5 4]] 

Shape:	(2, 2)
Rank:	2



In [ ]:
G = np.array([
    [1,1,3],
    [2,2,4]
      
])
describe_mat(G)

Matrix:
 [[1 1 3]
 [2 2 4]] 

Shape:	(2, 3)
Rank:	2



In [ ]:
## Declaring 

In [ ]:
H = np.array ([1,2,3,4,5])
describe_mat(H)

Matrix:
 [1 2 3 4 5] 

Shape:	(5,)
Rank:	1



## Categorizing matrices

A categorizing matrix classifies all situations in the model by assessing whether the anticipated value corresponds to the actual value. The categorization matrix is a commonly used technique for evaluating statistical models; it is also known as a confusion matrix.

### Row and Column Matrices

The phrases "row and column matrices" and "row and column vectors are commonly interchangeable. Row and Column matrices are prominent in terms of vector and matrix calculations. Moreover, row and column matrices can also depict the rows and columns of broader subspaces. As a result, row matrices would be $i \times 1$, whereas row matrices would be $1 \times j$.

In [ ]:
## Decalring a Row Matrix

rowmatrix1D = np.array([
    1, 3, 2
]) ## this is a 1-D Matrix with a shape of (3, ), it's not really considered as a row matrix.
row_mat_2D = np.array([
    [1,2,3, -4]
]) ## this is a 2-D Matrix with a shape of (1,3)
describe_mat(rowmatrix1D)
describe_mat(row_mat_2D)

Matrix:
 [1 3 2] 

Shape:	(3,)
Rank:	1

Matrix:
 [[ 1  2  3 -4]] 

Shape:	(1, 4)
Rank:	2



In [ ]:
## Declaring a Column Matrix

col_mat = np.array([
    [1],
    [2],
    [5]
]) ## this is a 2-D Matrix with a shape of (3,1)
describe_mat(col_mat) 

Matrix:
 [[1]
 [2]
 [5]] 

Shape:	(3, 1)
Rank:	2



### Square Matrices

###### When the number of both the columns and rows are equal, They are known as Square Matrix, also called as an n x n matrix.

In [ ]:
def describe_mat(matrix):
  is_square = True if matrix.shape[0] == matrix.shape[1] else False
  print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.ndim}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')

In [ ]:
square_mat = np.array ([
      [1,2,5],
      [3,3,8],
      [6,1,7]
])

non_square_mat = np.array([
      [1,2,5],
      [3,3,8]
])
describe_mat(square_mat)
describe_mat(non_square_mat)

Matrix:
[[1 2 5]
 [3 3 8]
 [6 1 7]]

Shape:	2
Rank:	2
Is Square: True

Matrix:
[[1 2 5]
 [3 3 8]]

Shape:	2
Rank:	2
Is Square: False



### **According to element and matrix**



###**Null Matrix**

The null matrix is the additive identity of any matrix; that is why it is advantageous. Also, adding a null matrix to any matrix does not influence the value of the matrix; therefore, recognized as an additive identity.

In [ ]:
def describe_mat(matrix):
  if matrix.size > 0:
    is_square = True if matrix.shape[0] == matrix.shape[1] else False
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.ndim}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')
  else:
    print('Matrix is Null')

In [ ]:
null_mat = np.array([])
describe_mat(null_mat)

Matrix is Null


### **Zero Matrix**

Zero matrix is an additive identity used for matrix addition. It is a matrix that is completely composed of Zero components

###### A zero matrix can be any rectangular matrix but with all elements having a value of 0.

In [ ]:
zero_mat_row = np.zeros((1,2))
zero_mat_sqr = np.zeros((2,2))
zero_mat_rct = np.zeros((3,2))

print(f'Zero Row Matrix: \n{zero_mat_row}')
print(f'Zero Square Matrix: \n{zero_mat_sqr}')
print(f'Zero Rectangular Matrix: \n{zero_mat_rct}')

Zero Row Matrix: 
[[0. 0.]]
Zero Square Matrix: 
[[0. 0.]
 [0. 0.]]
Zero Rectangular Matrix: 
[[0. 0.]
 [0. 0.]
 [0. 0.]]


### **Once Matrix**

###### A ones matrix, just like the zero matrix, can be any rectangular matrix but all of its elements are 1s instead of 0s.

In [ ]:
ones_mat_row = np.ones((1,2))
ones_mat_sqr = np.ones((2,2))
ones_mat_rct = np.ones((3,2))

print(f'Ones Row Matrix: \n{ones_mat_row}')
print(f'Ones Square Matrix: \n{ones_mat_sqr}')
print(f'Ones Rectangular Matrix: \n{ones_mat_rct}')

Ones Row Matrix: 
[[1. 1.]]
Ones Square Matrix: 
[[1. 1.]
 [1. 1.]]
Ones Rectangular Matrix: 
[[1. 1.]
 [1. 1.]
 [1. 1.]]


### **Diagonal Matrix**

A Diagonal Matrix is a square matrix wherein all elements other than the primary diagonal are zeros, and the principal diagonal elements might be zeros or non-zeroes.

In [ ]:
np.array([
    [2,0,0],
    [0,3,0],
    [0,0,5]
])
# a[1,1], a[2,2], a[3,3], .... a[n-1,n-1]

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

In [ ]:
d = np.diag([2,3,5,7])
d.shape[0] == d.shape[1]
d

array([[2, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 7]])

### **Identity Matrix**

A square matrix with the elements of the main diagonal identical with one and the other components equal to zero are known as an identity matrix. In the Python programming language, array objects are detailed lists for vector and matrix calculation.

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### **Upper Triangular Matrix**

In an Upper triangular matrix, all items below the main diagonal are zero in. Additionally, the matrix with zero components above the main diagonal is referred to as a lower triangular matrix.

In [ ]:
np.array([
    [1,2,3,4],
    [0,3,1,-1],
    [0,0,5,2],
    [0,0,0,2]
])

array([[ 1,  2,  3,  4],
       [ 0,  3,  1, -1],
       [ 0,  0,  5,  2],
       [ 0,  0,  0,  2]])

### **Lower Triangular Matrix**

A matrix with no values above the diagonal is defined as a lower triangular matrix.

In [ ]:
np.array([
  [1,2],
  [2,1]
])

array([[1, 2],
       [2, 1]])

In [ ]:
np.array([
    [1,0,0],
    [5,3,0],
    [7,8,5]
])

array([[1, 0, 0],
       [5, 3, 0],
       [7, 8, 5]])

### **Practice**

###### 1. Given the linear combination below, try to create a corresponding matrix representing it.


:$$\theta = 5x + 3y - z$$


$$
\theta = \begin{bmatrix} 5  &  3 & -1\end{bmatrix} \\
$$

In [ ]:
theta = np.array([
    [5, 3, -1]
   
])
theta

array([[ 5,  3, -1]])

###### 2. Given the system of linear combinations below, try to encode it as a matrix. Also describe the matrix.


$$
A = \left\{\begin{array}
5x_1 + 2x_2 +x_3\\
4x_2 - x_3\\
10x_3
\end{array}\right.
$$


$$
A=\begin{bmatrix} 1 & 2 & 1 \\ 0 & 4 & -1 \\ 0 & 0 & 10\end{bmatrix}
$$

###### 3. Given the matrix below, express it as a linear combination in a markdown and a LaTeX markdown


In [ ]:
G = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])

$$
G = \begin{bmatrix} 1 & 7 & 8 \\ 2 & 2 & 2 \\ 4 & 6 & 7\end{bmatrix}
$$

$$
G = \left\{
    \begin{array}\
        1 + 7 + 8 \\
        2 + 2 + 2 \\
        4 + 6 + 7 \\
    \end{array}
\right. \\
 $$

###### 4. Given the matrix below, display the output as a LaTeX markdown also express it as a system of linear combinations.



In [ ]:
H = np.tril(G)
H


array([[1, 0, 0],
       [2, 2, 0],
       [4, 6, 7]])

$$
H = \left\{
    \begin{array}\
             1 \\
           2 + 2 \\
         4 + 6 + 7 \\
    \end{array}
\right. \\
 $$

$$
H = \begin{bmatrix} 1 & 0 & 0 \\ 2 & 2 & 0 \\ 4 & 6 & 7\end{bmatrix}
$$

### **Matrix Algebra**

Matrix algebra is a notation for simultaneous equations that simplifies their presentation and solution. It may be used to generate a brief explanation of a structural issue and a mathematical structure model.

#### Addition

In [ ]:
A = np.array([
    [1,2],
    [2,3],
    [4,1]
])
B = np.array([
    [2,2],
    [0,0],
    [1,1]
])
A+B

array([[3, 4],
       [2, 3],
       [5, 2]])

In [ ]:
3+A ##Broadcasting
# 3*np.ones(A.shape)+A

array([[4, 5],
       [5, 6],
       [7, 4]])

In [ ]:
P = np.array([
    [5,7,2],
    [2,3,3],
    [4,1,0]
])
Q = np.array([
    [2,2,-3],
    [0,0,1],
    [1,1,0-3]
])
P + 2*Q

array([[ 9, 11, -4],
       [ 2,  3,  5],
       [ 6,  3, -6]])

#### Subtraction

In [ ]:
A-B

array([[-1,  0],
       [ 2,  3],
       [ 3,  0]])

In [ ]:
2-B

array([[0, 0],
       [2, 2],
       [1, 1]])

#### Element-Wise Multiplication

In [ ]:
A*B 
np.multiply(B,A)

array([[2, 4],
       [0, 0],
       [4, 1]])

In [ ]:
5*A

array([[ 5, 10],
       [10, 15],
       [20,  5]])

## **Activity**

### **Task 1**

Create a function named `mat_desc()` that througouhly describes a matrix, it should: <br>
1. Displays the shape, size, and rank of the matrix. <br>
2. Displays whether the matrix is square or non-square. <br>
3. Displays whether the matrix is an empty matrix. <br>
4. Displays if the matrix is an identity, ones, or zeros matrix <br>

Use 5 sample matrices in which the actions and methods you have done. Present your results in the results ir shapes are not lower than $(3,3)$.
In your methodology, create a flowchart discuss the section showing the description of each matrix you have declared.

In [ ]:
def mat_desc(matrix):
  mat = np.array(matrix)
  f = False
  t = True

  one = np.ones((matrix.shape[0], matrix.shape[1])),
  zero = np.zeros((matrix.shape[0], matrix.shape[1]))

  is_square = t if matrix.shape[0] == matrix.shape[1] else f
  is_Empty = t if(matrix.shape[0] == 0 and matrix.shape[1] == 0) else f
  is_uno = t if((one == matrix).all()) else f
  is_zero = t  if((zero == matrix).all()) else f

  print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nSize:\t{matrix.size}\nRank:\t{np.linalg.matrix_rank(mat)}\nIs Square: {is_square}\nMatrix is Empty: {is_Empty}\nMatrix is an ones matrix: {is_uno}\nMatrix is an zeros matrix: {is_zero}')

  if matrix.shape[0]==matrix.shape[1]:
    is_iden = t if (np.identity(matrix.shape[0]) == matrix).all() else f
    print(f'Matrix is an Identity matrix: {is_iden}')
  else:
    print(f'Matrix is an Identity matrix: {f}')

In [ ]:
A = np.array([
    [0,0,1,8],
    [1,1,6, 5],
    [1,0,5, 7]
])
mat_desc(A)

In [ ]:
B = np.array([
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 1]
])
mat_desc(B)

Matrix:
[[1 0 0]
 [0 1 0]
 [0 0 1]]

Shape:	(3, 3)
Size:	9
Rank:	3
Is Square: True
Matrix is Empty: False
Matrix is an ones matrix: False
Matrix is an zeros matrix: False
Matrix is an Identity matrix: True


In [ ]:
C = np.array([
    [0, 0, 0],
    [0, 0, 0],
    [0, 0, 0]
])
mat_desc(C)

Matrix:
[[0 0 0]
 [0 0 0]
 [0 0 0]]

Shape:	(3, 3)
Size:	9
Rank:	0
Is Square: True
Matrix is Empty: False
Matrix is an ones matrix: False
Matrix is an zeros matrix: True
Matrix is an Identity matrix: False


In [ ]:
D = np.array([
    [3,6,5,8,7],
    [2,8,5,6,2],
    [1,0,5,8,4]
])
mat_desc(D)

Matrix:
[[3 6 5 8 7]
 [2 8 5 6 2]
 [1 0 5 8 4]]

Shape:	(3, 5)
Size:	15
Rank:	3
Is Square: False
Matrix is Empty: False
Matrix is an ones matrix: False
Matrix is an zeros matrix: False
Matrix is an Identity matrix: False


In [ ]:
E = np.array([
    [1, 1, 1],
    [1, 1, 1],
    [1, 1, 1]
])
mat_desc(E)

Matrix:
[[1 1 1]
 [1 1 1]
 [1 1 1]]

Shape:	(3, 3)
Size:	9
Rank:	1
Is Square: True
Matrix is Empty: False
Matrix is an ones matrix: True
Matrix is an zeros matrix: False
Matrix is an Identity matrix: False


### **Task 2**

Create a function named `mat_operations()` that takes in two matrices a input parameters it should:<br>
 1. Determines if the matrices are viable for operation and returns your own error message if they are not viable.
 2. Returns the sum of the matrices.
 3. Returns the differen of the matrices.
 4. Returns the element-wise multiplication of the matrices.
 5. Returns the element-wise division of the matrices.

Use 5 sample matrices in which their shapes are not lower than $(3,3)$.
In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [ ]:
def mat_operations(mat1,mat2):
  if (len(mat1)<3 and len(mat1[0])<3) or (len(mat2)<3 and len(mat2[0])<3):
    return 'Invalid Matrices. Please try again.'
  
  elif (len(mat1) !=len(mat2)) and (len(mat1[0]) != len(mat2[0])):
    return 'Invalid Matrices. Please try again.'

  else:
    #Viable Matrices
    print('1. Add Matrices (+) ')
    print('2. Subtract Matrices (-) ')
    print('3. Element-Wise Multiplication (*) ')
    print('4. Element-Wise Division (/) ')

    choice = int(input("Please Enter Desired Operation: "))
    result = [[None for _ in range(len(mat1))] for _ in range(len(mat1[0]))]

    if choice==1:
      #Perform Addition
      for i in range(len(mat1)):
        for j in range(len(mat1[0])):
          result[i][j] = round(mat1[i][j] + mat2[i][j],3)

      return 'The Sum of the Matrices are '+str(result)

    if choice==2:
      #Perform Subtraction
      for i in range(len(mat1)):
        for j in range(len(mat1[0])):
          result[i][j] = round(mat1[i][j] - mat2[i][j],2)

      return 'The Difference of the Matrices are '+str(result)

    if choice==3:
      #Perform Else-Wise Multiplication
      for i in range(len(mat1)):
        for j in range(len(mat1[0])):
          result[i][j] = round(mat1[i][j] * mat2[i][j],4)

      return 'The Product of the Matrices are '+str(result)

    if choice==4:
      #Perform Else-Wise Division
      for i in range(len(mat1)):
        for j in range(len(mat1[0])):
          result[i][j] = round(mat1[i][j] / mat2[i][j],2)

      return 'The Quotient of the Matrices are '+str(result)

    else:
      return 'No Operation Available. Please try again. '

In [ ]:
K = [[10.23,-8, 4.7843],
    [0 ,-2.09, 3.867],
    [0 ,1, 5]]

P = [[2, -9.003, 7],
    [0, 1.454, 3.097],
    [1,4,0]]
    
print(mat_operations(K,P))

1. Add Matrices (+) 
2. Subtract Matrices (-) 
3. Element-Wise Multiplication (*) 
4. Element-Wise Division (/) 
Please Enter Desired Operation: 3
The Product of the Matrices are [[20.46, 72.024, 33.4901], [0, -3.0389, 11.9761], [0, 4, 0]]


In [ ]:
Z = [[10,8],
    [0 ,2]]


L = [[2,9],
    [0,1]]
     
print(mat_operations(Z,L))

Invalid Matrices. Please try again.


In [ ]:
L = [[5, 10, 3],
     [2, 5, 8]]

I = [[ 2, 6],
     [2, 8]]

print(mat_operations(L,I))

Invalid Matrices. Please try again.


In [ ]:
D = [[30.432, -15, 5.21],
    [5.25, 2.34, 5.89],
    [2.00, 4.98, -2]]


B = [[-5.55, -3.22, 5],
     [5, 1, 1],
    [2, 2, 2]]
     
print(mat_operations(D,B))

1. Add Matrices (+) 
2. Subtract Matrices (-) 
3. Element-Wise Multiplication (*) 
4. Element-Wise Division (/) 
Please Enter Desired Operation: 4
The Quotient of the Matrices are [[-5.48, 4.66, 1.04], [1.05, 2.34, 5.89], [1.0, 2.49, -1.0]]


In [ ]:
Y = [[30, -16, 5],
    [25, 10, 14],
    [-50, -30, 15]]


K = [[2, 2, 2],
     [2, 2, 2],
    [2, 2, 2]]
     
print(mat_operations(Y,K))

1. Add Matrices (+) 
2. Subtract Matrices (-) 
3. Element-Wise Multiplication (*) 
4. Element-Wise Division (/) 
Please Enter Desired Operation: 2
The Difference of the Matrices are [[28, -18, 3], [23, 8, 12], [-52, -32, 13]]


In [ ]:
P = [[30, -16, 5],
    [25, 10, 14],
    [2, 2, 10],
    [-50, -30, 15]]


J = [[2, 2],
     [2, 2, 2],
    [2, 2, 2]]
     
print(mat_operations(P,J))

Invalid Matrices. Please try again.


In [ ]:
F = [[2, 5, 7],
     [3, 4, 5],
     [6, 4, 2]]

S = [[3, 4, 7],
     [5, 2, 1],
     [2, 7, 2]]

print(mat_operations(F,S))

1. Add Matrices (+) 
2. Subtract Matrices (-) 
3. Element-Wise Multiplication (*) 
4. Element-Wise Division (/) 
Please Enter Desired Operation: 1
The Sum of the Matrices are [[5, 9, 14], [8, 6, 6], [8, 11, 4]]


In [ ]:
D = [[2, 3, 4, 7],
     [5, 7, 4, 3],
     [2, 8, 5, -2],
     [2, 3, 6, 8, 10]]

E = [[1,2, 4, 3],
     [1, 1, 1, 2],
     [2, 3, 5, 8],
     [4, 3, 2, 1]]

print(mat_operations(D,E))

1. Add Matrices (+) 
2. Subtract Matrices (-) 
3. Element-Wise Multiplication (*) 
4. Element-Wise Division (/) 
Please Enter Desired Operation: 4
The Quotient of the Matrices are [[2.0, 1.5, 1.0, 2.33], [5.0, 7.0, 4.0, 1.5], [1.0, 2.67, 1.0, -0.25], [0.5, 1.0, 3.0, 8.0]]


In [ ]:
S = [[ 5, 4, 9, 10, 5, 2],
     [2, 3, 4, 6, 8, 3],
     [2, 5, 3, 2, 1, 5],
     [4, 2, 2, 1, 0],
     [5, 2, 1, 5, 3,2 ]]

U =  [[2, 4, 1, 0, -5, -2.3456],
     [2.00, -3.22, 4.21, -6, 8.22, 3.987],
     [2, -5.55, 3.00, -2, 1.00, 5.987],
     [-4, 2.21, 3, 5, 0],
     [-5, 1, 1, 2, 2, 1 ]]

print(mat_operations(S,U))

1. Add Matrices (+) 
2. Subtract Matrices (-) 
3. Element-Wise Multiplication (*) 
4. Element-Wise Division (/) 
Please Enter Desired Operation: 5
No Operation Available. Please try again. 
